#!/usr/bin/python3
# coding: utf8
# -----------------------------------------------------------------------
#
# pcron - a periodic cron-like job scheduler.
# Copyright (C) 2009-2015 Lars Gustäbel <lars@gustaebel.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# -----------------------------------------------------------------------

import os
import logging
import optparse

from libpcron import __version__, __copyright__
from libpcron.shared import DaemonContext
from libpcron.scheduler import Scheduler


if __name__ == "__main__":
    parser = optparse.OptionParser(version="%%prog %s - %s" % (__version__, __copyright__))
    parser.add_option("-f", "--foreground", action="store_false", dest="daemon", default=True,
            help="do not fork to the background and write log messages to stderr")
    parser.add_option("-d", "--directory", metavar="NAME", default="~/.pcron",
            help="the name of the configuration directory, default is %default")
    opts, args = parser.parse_args()

    opts.directory = os.path.expanduser(opts.directory)

    with DaemonContext(os.path.join(opts.directory, "pcron.pid"), daemonize=opts.daemon):
        with Scheduler(opts) as scheduler:
            scheduler.mainloop()

